### PR TITLE
Add Azure iaas-settings Example

### PR DESCRIPTION
**Pull request by apeschel**
This new example using the existing AWS and vSphere examples as a
template, but updates them with Azure specific cloud_properties.

### CODE REVIEW

**Comment by jpalermo** [comment]
Sorry @apeschel, I was a bit too quick to merge this in. We'll need you to sign and accept the CLA before we can merge it.

Once you do that, go ahead and create a new pull request.

Thanks!

**Comment by GarfieldIsAPhilosopher** [comment]
Hi @apeschel,

Thanks for your pull request. We'd love to incorporate this, but still need confirmation that you have an individual or corporate CLA in place.
https://www.cloudfoundry.org/community/contribute/

We're going to close this out, but please re-open when you have a CLA in-place.

Thanks,

Difan && Andrew

**Comment by menicosia** [comment]
@apeschel Just pinging back one final time; we'd be happy to merge this in, but we can't do so without a CLA. Is there anything else we can do to make this easier for you?

**Comment by apeschel** [comment]
@menicosia I'm trying to get a company CLA, but I'm having trouble getting the paper work through. My apologies on the delay -- I'm still working on getting it through.

**Pull request merged**
