### PR TITLE
Configureable slow query threshold

### PR DESCRIPTION
**Pull request by ldangeard-orange**
To configure slow query threshold, I add a long_query_time property to adjust the value at best.
By default, 10s is too long for a transactional type application. The value can be specified to a resolution of microseconds.
Slow queries are log in `/var/vcap/sys/log/mysql/mysql_slow_query.log`.

/CC @axelfauvel @gberche-orange

### CODE REVIEW

**Comment by menicosia** [comment]
Hi @alexjh @gberche-orange,

Thank you for contributing this!

This suggestion seems to make sense, I've prioritized it for the team to look into merging it soon-ish. (We're currently super occupied with the TLS epic.) They may have some feedback, or wish to do some additional work to make sure it's represented in CI.

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by gberche-orange** [comment]
Thanks Marco!

**Comment by gberche-orange** [comment]
sorry that we overlooked running the unit tests and updating the [my.cnf.erb.shasum](https://github.com/cloudfoundry/cf-mysql-release/blob/develop/jobs/mysql/templates/my.cnf.erb.shasum)
we'll push new commits to fix this.

/CC @ldangeard-orange

**Comment by gberche-orange** [comment]
@menicosia BTW, is there a public CI for the mysql (as we would try to run a copy of the [cf-mysql-ci](https://github.com/cloudfoundry-incubator/cf-mysql-ci) prior to submitting our PR)  ? I have run into https://core-services.ci.cf-app.com/ but can't see any public pipelines there yet.

**Comment by jpalermo** [comment]
Hey @gberche-orange. Currently the CI is not public. [cf-mysql-ci](https://github.com/cloudfoundry-incubator/cf-mysql-ci) is open source, although the amount of infrastructure and setup needed to get it up and running would probably make it prohibitive to run the pipelines yourself.

(https://github.com/cloudfoundry-incubator/cf-mysql-ci) is more intended as a demonstration of how we run tests, and possibly some of the scripts in there are useful if you try to implement tests of your own.

**Comment by gberche-orange** [comment]
thanks @jpalermo for this clarification.

**Comment by gberche-orange** [comment]
> Once you've publicized your membership, one of the owners of this repository can close and reopen this pull request, and dreddbot will take another look.

@ldangeard-orange is now covered by Orange CCLA as a public member of https://github.com/orange-cloudfoundry . Should be fine to retrigger the dreddbot by closing & reopening this issue.

**Comment by menicosia** [comment]
@ldangeard-orange @gberche-orange this will be included in [v36.10.0](https://github.com/cloudfoundry/cf-mysql-release/releases/tag/v36.10.0)

**Comment by gberche-orange** [comment]
thanks @menicosia and core services team!

**Pull request merged**
