### PR TITLE
Allow skipping of acceptance tests by using regex

### PR DESCRIPTION
**Pull request by kei-yamazaki**
Allow skipping of acceptance tests by using regex.
Porting from diego-release.

### CODE REVIEW

**Comment by menicosia** [comment]
Hi @kei-yamazaki,

We understand why this might be useful for diego-release, but in general, the MySQL acceptance tests are pretty reliable. Can you give us an idea of what it is that you would want to skip?

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by kei-yamazaki** [comment]
@menicosia, Thanks for reply

I understand cf-mysql-release acceptance tests are reliable.
Current acceptance tests includes plan migration tests, and this tests needs one or more plan.
But we register only one plan, so can not pass plan migration tests.

**Comment by ljfranklin** [comment]
@kei-yamazaki You are correct that the full set of acceptance-tests does require a second plan to test the quota-enforcer component. However, our acceptance-tests errand does not run this test by default. This test will only be run if you set `jobs.acceptance_tests.properties.smoke_tests_only` to `false` in your deployment manifest. The default acceptance-tests errand does not require multiple plans as of cf-mysql v23.

This smoke tests vs acceptance tests distinction is definitely confusing. I created a [bug](https://www.pivotaltracker.com/story/show/110892170) in our backlog to clear this up a bit.

**Comment by bencalegari** [comment]
@kei-yamazaki Closing this ticket as we think your use case is covered here based on Lyle's comment. If you have any other issues or disagree, please feel free to reopen it. Thanks!

**Pull request closed without merging**
