### PR TITLE
Added a security rule for bosh-lite deployments, and fixed the README…

### PR DESCRIPTION
**Pull request by jasonjackson**
Security groups for bosh-lite deployments *are* needed for the acceptance tests to pass, and for apps to connect to the MySQL proxy.

Fixed the README and added a bosh-lite-security-rule.json that matches the manifest for easy setup.

### CODE REVIEW

**Comment by jasonjackson** [comment]
Individual CLA emailed.

**Comment by menicosia** [comment]
Hi @jasonjackson,

I'm sorry, it looks like you've made this PR against the `master` branch where this project traditionally does work against the `develop` branch. Would you mind rebasing against `develop`?

You've caught us between releases, so the documentation you'd need to know this is unfortunately... on the develop branch. There's more information about how and why in the [Branch workflow](https://github.com/cloudfoundry/cf-mysql-release/blob/develop/CONTRIBUTING.md#branch-workflow) section of our CONTRIBUTING doc.

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by jasonjackson** [comment]
Sorry, I had already deleted this repo from my side.  New repo with the
changes is at:

https://github.com/jasonjackson/cf-mysql-release

On develop branch..

On Tue, Jul 7, 2015 at 2:50 AM, Marco Nicosia <notifications@github.com>
wrote:

> Hi @jasonjackson <https://github.com/jasonjackson>,
>
> I'm sorry, it looks like you've made this PR against the master branch
> where this project traditionally does work against the develop branch.
> Would you mind rebasing against develop?
>
> You've caught us between releases, so the documentation you'd need to know
> this is unfortunately... on the develop branch. There's more information
> about how and why in the Branch workflow
> <https://github.com/cloudfoundry/cf-mysql-release/blob/develop/CONTRIBUTING.md#branch-workflow>
> section of our CONTRIBUTING doc.
>
> Marco Nicosia
> Product Manager
> Pivotal Software, Inc.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudfoundry/cf-mysql-release/pull/70#issuecomment-118976802>
> .
>



-- 

Most people are born and years later die without really having lived at
all. They play it safe and tiptoe through life with no aspiration other
than to arrive at death safely.

-- Tony Campolo, "Carpe Diem"

**Comment by ljfranklin** [comment]
Closing this as a duplicate of https://github.com/cloudfoundry/cf-mysql-release/pull/71/files.

**Pull request closed without merging**
